# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='file_type',
        ),
    ]
