# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_movie_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_favorite',
        ),
    ]
