# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_movie_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
