# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20180624_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Western',
        ),
    ]
