# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20180624_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
